services:
  verdaccio:
    image: verdaccio/verdaccio
    ports:
    - '4873:4873'
    volumes:
    - './config:/verdaccio/conf'
    networks:
    - node-network
networks:
  node-network:
    driver: bridge
